version: '3.1'
services:
  mongo:
    image: mongo:jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - arieltintel      
  mongo-express: 
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root #Usuario: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: root #Login: 'pass'
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - arieltintel

networks:
  arieltintel:
    driver: bridge
