version: '3.3'
services:
  db:
    image: mysql:8.0.31-oracle
    container_name: mysql_localhost
    volumes:
      - db-data:/var/lib/mysql_localhost
    networks:
      - cliente-compose-network
#    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: clientes_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - cliente-compose-network
    links:
      - db
    ports:
      - "8000:80"

volumes:
  db-data:
    name: mysql_localhost

networks:
  cliente-compose-network:
    driver: bridge
