services:
  redis:
    image: redis:latest
    container_name: redis_localhost
    ports:
     - 6379:6379
    volumes:
      - db-data:/var/lib/redis_localhost
      
volumes:
  db-data:
    name: redis_localhost
